### ISSUE TITLE
Build the basic app layout

### ISSUE THREAD

**Issue by StanBankras** [ofahchouch-gh/gyro-project#16]
Create the header, container and footer elements that wrap the application.

**Comment by Jelmerovereem** [comment]
- [ ] Header (Jelmer)
- [ ] Footer

**Comment by StanBankras** [comment]
[ ] Container element that wraps the application

**Comment by Jelmerovereem** [comment]
Finished header for now 803d172a4f89db81e342c0cc8a33f4594e1104a7

**Comment by Jelmerovereem** [comment]
@StanBankras What will the footer include? Some basic copyright info or what do you suggest?

**Comment by StanBankras** [comment]
@Jelmerovereem I think we don't need a footer for now, it will only clutter the interface.
