### ISSUE TITLE
Get last 5 training sessions of a clinician

### ISSUE THREAD

**Issue by StanBankras** [ofahchouch-gh/gyro-project#162]
- [x] Write logic for sorting trainings & the last 5
- [x] Create UI for showing these

**Comment by Jelmerovereem** [comment]
What was your intention with this exactly?

**Comment by StanBankras** [comment]
> You mean this section?
> ![last training sessions](https://user-images.githubusercontent.com/58043913/121195570-00c90b00-c870-11eb-867c-fbe3c97e20b0.png)

Yes
