### ISSUE TITLE
Destruct the req.body object first for better readability

### ISSUE THREAD

**Issue by joostf** [ofahchouch-gh/gyro-project#174]
https://github.com/ofahchouch-gh/gyro-project/blob/ddc5a0432b5fbbc823ac5603bfa5ec5bfb0c357e/server/routes/PatientRouter.js#L20-L28

```
const {firstName, lastName, ......} = req.body

const patient = {firstName, lastName, ......}
```

**Comment by ofahchouch-gh** [comment]
Thanks! Didn't know about that trick! Will use it from now on :).
