### ISSUE TITLE
Select perturbations on dartboard and filter them on results timeline

### ISSUE THREAD

**Issue by Jelmerovereem** [ofahchouch-gh/gyro-project#188]
- [x] Click/touch events to detect where user clicks on the dartboard
- [x] Filter based on clicked area
- [x] Update timeline based filteredPoints

**Comment by StanBankras** [comment]
Added click/touch events to detect where user clicks on the darboard. Implemented the filteredPoints 59da0796345e54ec3bf4c7050ac8246d8a7e3edb

**Comment by StanBankras** [comment]
Points are all being filtered now and indication of selected area is given on the results dartboard.
