### ISSUE TITLE
Log in email-address is case sensitive. Bug

### ISSUE THREAD

**Issue by Jelmerovereem** [ofahchouch-gh/gyro-project#205]
For example:
User email: john.doe@gmail.com

_John.doe@gmail.com_ will not work
_john.doe@gmail.com_ does work

But they just both have to work, I think a simple `email.toLowerCase()` will do the job just fine.

**Comment by StanBankras** [comment]
Fix in a4c181f7814d30308182147c376c64d346c42aaf
