### ISSUE TITLE
Implement training logic

### ISSUE THREAD

**Issue by Jelmerovereem** [ofahchouch-gh/gyro-project#35]
The three different trainings have different logic.

* Continuous -> live visualization should be constant
* Perturbation -> not sure, maybe the random perturbations should be checked by default here?
* Assistance -> not sure, maybe the random perturbations should be unchecked by default here?

**Comment by Jelmerovereem** [comment]
Training choice needs to be stored or something like that

**Comment by StanBankras** [comment]
> Training choice needs to be stored or something like that. Maybe with a parameter in the url?

Yes, I will make this happen

**Comment by Jelmerovereem** [comment]
I'll work on the logic per training

**Comment by StanBankras** [comment]
Closing this issue for now, since we changed plans.
