### ISSUE TITLE
Decide on & document JSON communication between client and server

### ISSUE THREAD

**Issue by StanBankras** [ofahchouch-gh/gyro-project#6]
* What commands should the frontend send?
* How does the JSON look?

**Comment by StanBankras** [comment]
This was my idea for the websockets commands that can be sent. Please check it @ofahchouch-gh @Jelmerovereem 

[https://github.com/ofahchouch-gh/gyro-project/blob/develop/server/README.md](https://github.com/ofahchouch-gh/gyro-project/blob/develop/server/README.md)

**Comment by Jelmerovereem** [comment]
Looks great!
