### ISSUE TITLE
Idea for error handling?

### ISSUE THREAD

**Issue by TuriGuilano** [ofahchouch-gh/gyro-project#90]
https://github.com/ofahchouch-gh/gyro-project/blob/109708389835ce7401345251f4ff54444639de0f/server/services/MongooseService.js#L3-L19

Maybe it's an idea to create a custom error handling class? Or wrap the function inside a try catch block or so? If you have other thoughts - let me know

**Comment by TuriGuilano** [comment]
Since it's a class - you probably run your error handling elsewhere? Can't find it 123..

**Comment by StanBankras** [comment]
@ofahchouch-gh maybe you can take a look at error handling here? I think you're most into this part.

**Comment by ofahchouch-gh** [comment]
Yeah i will add a try catch block :)! Thanks for the feedback @TuriGuilano !
